extends RefCounted
class_name PoSheets

## Erzeugt von tools/build_po.py - nicht von Hand aendern.
## Je Eintrag: Dateiname ohne Endung -> Anzahl Spalten (= Frames).

const CELL := 48
const ROWS := 5   ## Sued, Suedost, Ost, Nordost, Nord

const SHEETS := {
	"Character0_Damage": 2,
	"Character0_DamageHoldingTool": 2,
	"Character0_DamageHoldingTool_Axe": 2,
	"Character0_DamageHoldingTool_FishingPole": 2,
	"Character0_DamageHoldingTool_Hammer": 2,
	"Character0_DamageHoldingTool_PickAxe": 2,
	"Character0_DamageHoldingTool_Shield": 2,
	"Character0_DamageHoldingTool_Showel": 2,
	"Character0_DamageHoldingTool_Sword": 2,
	"Character0_DamageHoldingTool_WaterCan": 2,
	"Character0_Die": 6,
	"Character0_Dig": 6,
	"Character0_Dig_Showel": 6,
	"Character0_Fish": 6,
	"Character0_Fish_Fishingpole": 6,
	"Character0_GetUp": 4,
	"Character0_GetUpHoldingTool": 4,
	"Character0_GetUpHoldingTool_Axe": 4,
	"Character0_GetUpHoldingTool_Fishingpole": 4,
	"Character0_GetUpHoldingTool_Hammer": 4,
	"Character0_GetUpHoldingTool_Pickaxe": 4,
	"Character0_GetUpHoldingTool_Shield": 4,
	"Character0_GetUpHoldingTool_Showel": 4,
	"Character0_GetUpHoldingTool_Sword": 4,
	"Character0_GetUpHoldingTool_WaterCan": 4,
	"Character0_Idle": 8,
	"Character0_IdleHoldingTool": 8,
	"Character0_IdleHoldingTool_Axe": 8,
	"Character0_IdleHoldingTool_Fishingpole": 8,
	"Character0_IdleHoldingTool_Hammer": 8,
	"Character0_IdleHoldingTool_Pickaxe": 8,
	"Character0_IdleHoldingTool_Shield": 8,
	"Character0_IdleHoldingTool_Showel": 8,
	"Character0_IdleHoldingTool_Sword": 8,
	"Character0_IdleHoldingTool_WaterCan": 8,
	"Character0_Interact": 3,
	"Character0_InteractHoldingTool": 3,
	"Character0_InteractHoldingTool_Axe": 3,
	"Character0_InteractHoldingTool_Fishingpole": 3,
	"Character0_InteractHoldingTool_Hammer": 3,
	"Character0_InteractHoldingTool_PickAxe": 3,
	"Character0_InteractHoldingTool_Shield": 3,
	"Character0_InteractHoldingTool_Showel": 3,
	"Character0_InteractHoldingTool_Sword": 3,
	"Character0_InteractHoldingTool_WaterCan": 3,
	"Character0_Run": 4,
	"Character0_Run_Axe": 4,
	"Character0_Run_Fishingpole": 4,
	"Character0_Run_Hammer": 4,
	"Character0_Run_PickAxe": 4,
	"Character0_Run_Shield": 4,
	"Character0_Run_Sword": 4,
	"Character0_Run_WaterCan": 4,
	"Character0_Sit": 4,
	"Character0_SitHoldingTool": 4,
	"Character0_SitHoldingTool_Axe": 4,
	"Character0_SitHoldingTool_Fishingpole": 4,
	"Character0_SitHoldingTool_Hammer": 4,
	"Character0_SitHoldingTool_Pickaxe": 4,
	"Character0_SitHoldingTool_Showel": 4,
	"Character0_SitHoldingTool_Sword": 4,
	"Character0_SitHoldingTool_WaterCan": 4,
	"Character0_Swing": 6,
	"Character0_Swing_Axe": 6,
	"Character0_Swing_Hammer": 6,
	"Character0_Swing_PickAxe": 6,
	"Character0_SwordAttack": 6,
	"Character0_SwordAttack_Sword": 6,
	"Character0_Walk": 6,
	"Character0_WalkHoldingTool": 6,
	"Character0_WalkHoldingTool_Axe": 6,
	"Character0_WalkHoldingTool_Fishingpole": 6,
	"Character0_WalkHoldingTool_Hammer": 6,
	"Character0_WalkHoldingTool_Pickaxe": 6,
	"Character0_WalkHoldingTool_Showel": 6,
	"Character0_WalkHoldingTool_Silver": 6,
	"Character0_WalkHoldingTool_Sword": 6,
	"Character0_WalkHoldingTool_WaterCan": 6,
}
